### ISSUE TITLE
Provide pure-floss build flavor

### ISSUE THREAD

**Issue by krt16s** [easytargetmixel/micopi_android#15]
Your recent version (3.5 commit, 3.6 tag) introduces a proprietary dependency, namely Google's play-services. While I can understand the motivation using ads, F-Droid cannot build non-free software. Could you provide a pure-floss gradle build flavor?

**Comment by easytargetmixel** [comment]
@krt16s I have added a branch "noads" without Google Play Services.

**Comment by krt16s** [comment]
Thank you very much, really appreciated!
