### ISSUE TITLE
Generate all contacts pictures

### ISSUE THREAD

**Issue by gsurrel** [easytargetmixel/micopi_android#3]
When choosing "Generate all contacts pictures, the app hangs for some time (I get two ANR dialogs) but afterwards, nothing new.

Also, I wonder if this feature overwrites the existing pictures or not.

**Comment by easytargetmixel** [comment]
The button now starts the Service that goes through all the contacts, generates images, if needed but does not YET assign them or generate notifications. Only by looking into the logs, you'll see that something is happening in the background.

The picture assignment method is there obviously but for now, disabled on purpose.

**Comment by ckm8** [comment]
Thanks for your efforts on this, loving the app.

Paul
